### ISSUE TITLE
JWS secret?

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#16]
Regarding [resources](http://sdmp.github.io/docs/resource/), when generating the signature, what is to be used as the secret?

Am I missing something about how JWS works?

**Comment by saibotsivad** [comment]
I think with https://github.com/sdmp/sdmp.github.io/pull/22 the documentation about resource is a bit more clear, but if it's not clear after that pull request is merged, please re-open this issue and I can write up a few more details. Maybe some examples would help?
