### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#17]
According to the [container page](http://sdmp.github.io/docs/container/)

```
When communicating between nodes and when publishing resources, 
the data is placed inside a JSON Web Signature (JWS) object. This 
JSON object is the SDMP container, and must be used for all 
communication and for all published content in the SDMP.
```

Is this the [container schema](https://github.com/sdmp/sdmp-schema/blob/master/schemas/container.json)?

Or is there some higher level wrapper for resources?

Also, what is the [payload schema](https://github.com/sdmp/sdmp-schema/blob/master/schemas/payload.json) for?  It seems to just be a thinner version of the container.

**Comment by saibotsivad** [comment]
I believe I have cleared this up with https://github.com/sdmp/sdmp.github.io/pull/22 where I describe "containers" and "resources" a bit more clearly.

Please feel free to re-open this issue once this pull request is merged, if it does not answer your question to your satisfaction.
