### ISSUE TITLE
Communication Serialization Format

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#18]
Which JWS format is used for sending documents?  The [TCP spec](http://sdmp.github.io/docs/tcp/) says:

```
Each node may at any time transmit to the other node. All 
transmitted communications must be in the format of a valid 
SDMP container.
```

It specifies that it must be in a valid container, but is that a [JWS Compact Serialization String](http://self-issued.info/docs/draft-ietf-jose-json-web-signature.html#CompactSerializationOverview), [JWS General JSON Serialization](http://self-issued.info/docs/draft-ietf-jose-json-web-signature.html#GeneralJSONSerialization), [JWS Flattened Serialization](http://self-issued.info/docs/draft-ietf-jose-json-web-signature.html#FlattenedJSONSerialization) or something else?

**Comment by saibotsivad** [comment]
I believe that this is closed with https://github.com/sdmp/sdmp.github.io/pull/22 where network communication is specified as being sent over "container" objects where the only allowed schema is the "encrypted" schema.

As of this writing:

> An encrypted network object is a container object where the only specified schema is the encrypted schema, and no other metadata is allowed. ... This JSON object is sent as the data stream for all network traffic after the session key is established.

**Comment by saibotsivad** [comment]
(Please feel free to re-open this issue once this pull request is merged, if it does not answer your question to your satisfaction.)
