### ISSUE TITLE
Include specs for private key?

### ISSUE THREAD

**Issue by saibotsivad** [sdmp/sdmp.github.io#25]
I started writing the command line implementation and realized I needed to output the private key in some form.

**Should the private key form be specified?**

My general thoughts are: yes. An application can decide the most appropriate way to store a private key, but a general form should be defined, that way exporting/importing between applications is easier.

**Comment by jmhobbs** [comment]
PEM?  It's pretty standard.  PKCS#8 lets you do encrypted or unencrypted.

**Comment by saibotsivad** [comment]
Yeah, good call. :+1:
