### ISSUE TITLE
Question & Proposal: Resource Type Identification

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#7]
Since there are very specific resource types, why are they not specified in the sdmp object somewhere?

I feel an `sdmp.type` or the like would be very useful for disambiguating resources, rather than relying on attribute detection, which seems to be the only option right now.

Additionally, if that is implemented, how do you feel about a namespace for general document extensions?

For instance, my `type` could be `sdmp.velvetcache.org/0.9/blog` and there could be some sort of document required specifying the purpose and presentation options there.

Kind of smells like XML, for better or worse.

**Comment by saibotsivad** [comment]
I originally had that thought as well, and based on some reading and thinking discarded it. Unfortunately, I didn't write down notes as to why it would be one way and not another, so I am thinking I will add some sort of `sdmp.type` property that is then extendable. I'm working on it now, but I probably won't have it done until mid-week.

**Comment by saibotsivad** [comment]
Closed via #14.
